# fly.toml app configuration file generated for fate-shift-api on 2025-10-17T04:26:13-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fate-shift-api'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  EPHE_PATH = 'ephemeris'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
