[phases.setup]
nixPkgs = ["python311", "curl"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "mkdir -p ephemeris",
  "curl -L -o ephemeris/sechiron.se1 https://github.com/aloistr/swisseph/raw/master/ephe/sechiron.se1",
  "curl -L -o ephemeris/seask10.se1 https://github.com/aloistr/swisseph/raw/master/ephe/seask10.se1",
  "curl -L -o ephemeris/seas_18.se1 https://github.com/aloistr/swisseph/raw/master/ephe/seas_18.se1"
]

[phases.build]

[start]
cmd = "uvicorn astro_api:app --host 0.0.0.0 --port $PORT"

[variables]
EPHE_PATH = "ephemeris"
